name: 'Continuous Integration'

on:
  push:
    branches: [master]
    tags: ['*']
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18.x
          - 20.x
          - 22.x

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install --frozen-lockfile --no-audit --no-fund

      - name: Lint source code
        run: npm run -- lint

      - name: Run tests
        run: |
          npm run -- test --silent --ci --coverage
          echo "COVERAGE=$(jq .total.lines.pct coverage/coverage-summary.json)" >> $GITHUB_ENV

      - name: Update coverage badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 4136c781b460695ffcbf3dd43f5b82bc
          filename: homebridge-my-gekko-coverage.json
          label: coverage
          message: ${{ env.COVERAGE }}%
          color: green

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build

    name: Publish
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 18.x
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install --frozen-lockfile --no-audit --no-fund

      - name: Publish package
        run: npm publish
